var json = {
	data: "root",
	children: [
		{
			data: "1",
			children: [
				{
					data: "A",
					children: []
				},
				{
					data: "B",
					children: []
				},
				{
					data: "C",
					children: [
						{
							data: "i",
							children: []
						},
						{
							data: "ii",
							children: []
						}
					]
				}
			]
		},
		{
			data: "2",
			children: [			
				{
					data: "A",
					children: []
				},
				{
					data: "B",
					children: []
				}
			]
		},
		{
			data: "3",
			children: []
		}
	]
}